from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship
from app.db import Base

class Subject(Base):
    """
    SQLAlchemy model representing a subject associated with a whiteboard.

    This model stores information about a subject, including its name and a refined
    summary provided by a language model (LLM). It is linked to a specific whiteboard
    via a foreign key relationship.

    Attributes:
        id (int): Primary key of the subject.
        whiteboard_id (int): Foreign key referencing the associated whiteboard's ID.
        name (str): The name of the subject.
        summary (str): An optional refined summary for the subject generated by an LLM.
        whiteboard (Whiteboard): Relationship to the associated whiteboard.
    """
    __tablename__ = "subjects"

    id = Column(Integer, primary_key=True, index=True)
    whiteboard_id = Column(Integer, ForeignKey("whiteboards.id"), nullable=False)  # Foreign key to Whiteboard
    name = Column(String, nullable=False)
    summary = Column(String, nullable=True)  # Refined summary provided by the LLM

    # Relationships
    whiteboard = relationship("Whiteboard", back_populates="subjects")
